### ISSUE TITLE
Must Add Space Before Ending Code Fence So That Following Header Appears In TOC

### ISSUE THREAD

**Issue by OdyAsh** [derlin/bitdowntoc#17]
If a language identifier (e.g., "Python") is used in a markdown's code fence, BitDownToc will not generate subsequent headers. Example:
(ignore the backticks (```) at the start and at the end, they are just used with `<pre>` tags to escape the inner code fence).

<pre>
```
# h1
abc
## h2
def

``` Python
    print("awesome video: https://www.youtube.com/watch?v=dQw4w9WgXcQ")
```

### h3
sad header

# h1 x 2
sadder header :[
```
</pre> 

will be converted to:

```
- [h1](#h1)
  * [h2](#h2)
```

However, the following:

<pre>
```
# h1
abc
## h2
def

``` Python
    print("awesome video: https://www.youtube.com/watch?v=dQw4w9WgXcQ")
 ```
(^^^ NOTICE THE SPACE)

### h3
sad header

# h1 x 2
sadder header :[
 ```
</pre> 

will be converted to:
```
- [h1](#h1)
  * [h2](#h2)
    + [h3](#h3)
- [h1 x 2](#h1-x-2)
```

Additionally, removing `Python` also gives the correct TOC

**Comment by derlin** [comment]
Hello and thank you for the reporting.

I believe the problem lies in the space between the three backticks and the language identifier. Usually, in markdown, you use `'''python` (replace single quotes with backticks) and not `''' Python`. Thus, what happens is the start of the first code block is not seen as a code block by BitDownToc, but the closing one is (and is thus treated as the beginning of a code block, thus ignoring everything until closed).

To avoid treating non-code blocks as code blocks, my rule is to use the regex `'''([a-z0-9]+)?`. I could change this and just treat whatever line starts with backticks as a code block, but I don't know if it may raise false positives. Do you see an example of a line beginning with three backticks which is NOT a code block?

I hesitate... In the meantime, you can simply change the `''' Python` to `'''python` and you should be fine (this is the standard markdown syntax for highlighted code blocks).

**Comment by OdyAsh** [comment]
First of all, thanks for the quick reply; I've learned something new about markdown! 😅

Regarding this:

I  Do you see an example of a line beginning with three backticks which is NOT a code block?

Not at the moment unfortunately. 

In any case, I think adding a simple "side-note" anywhere in the [website](https://derlin.github.io/bitdowntoc/) --- something like 'type "```python" instead of "``` python"' --- will help people avoid this mistake. 

However, as you said, what you suggested IS the standard markdown syntax, so you are completely justified to leave things as they are.

Thanks again for the quick reply! 🙌

**Comment by derlin** [comment]
Happy to help! 

Thanks for using bitdowntoc, and if you haven't already, star the repo 😊

**Comment by derlin** [comment]
Changed the way bitdowntoc detects code blocks in https://github.com/derlin/bitdowntoc/commit/82e14e35804c3721aa729c1c0f35562ea0c54f74, the issue should not happen again.
